# Generated by Django 4.2.5 on 2023-10-05 02:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Номер темы (индекс изделия)')),
                ('title', models.CharField(max_length=150, verbose_name='Название изделия')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Наименование работы')),
                ('start', models.DateTimeField(auto_now_add=True, verbose_name='Начало')),
                ('end', models.DateTimeField(verbose_name='Срок')),
                ('report', models.CharField(blank=True, max_length=150, null=True, verbose_name='Листок запуска/Извещение')),
                ('pages', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Количество листов')),
                ('performer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
                ('theme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='main.theme', verbose_name='Тема')),
            ],
        ),
    ]
