# Generated by Django 4.2.5 on 2023-10-06 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='title',
            field=models.CharField(default='-', max_length=150, verbose_name='Название изделия'),
        ),
    ]
