# Generated by Django 4.2.5 on 2023-10-05 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('announced', 'Запланирована'), ('in progress', 'В работе'), ('done', 'Выполнена'), ('canceled', 'Отменена')], default='announced', max_length=16, verbose_name='Статус работы'),
        ),
    ]
