# Generated by Django 4.2.5 on 2023-11-07 07:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_task_performer_alter_task_theme'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('-end', 'theme__slug', 'performer')},
        ),
        migrations.AlterModelOptions(
            name='theme',
            options={'ordering': ('slug',)},
        ),
        migrations.AlterField(
            model_name='task',
            name='start',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Начало'),
        ),
        migrations.AlterField(
            model_name='task',
            name='theme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='main.theme', verbose_name='Тема'),
        ),
    ]
