# Generated by Django 4.2.5 on 2023-10-03 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_hui_alter_user_email_alter_user_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ip',
            field=models.GenericIPAddressField(default='127.0.0.1', unique=True),
        ),
    ]
