# Generated by Django 4.2.5 on 2023-11-07 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_role_remove_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.role', verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='role',
            name='title',
            field=models.CharField(default='Инженер', max_length=32, verbose_name='Должность'),
        ),
    ]
