# Generated by Django 4.2.5 on 2023-11-08 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_department_depsublvl1_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='users.depsublvl2', verbose_name='Подразделение'),
            preserve_default=False,
        ),
    ]
