# Generated by Django 4.2.5 on 2023-11-09 02:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_department'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='depsublvl1',
            options={'default_related_name': 'department_lvl_1', 'ordering': ('slug',)},
        ),
        migrations.AlterModelOptions(
            name='depsublvl2',
            options={'default_related_name': 'department_lvl_2', 'ordering': ('slug',)},
        ),
        migrations.AddField(
            model_name='department',
            name='boss',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_for_boss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='department',
            name='sub_boss',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_for_sub_boss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='depsublvl1',
            name='boss',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='depsublvl2',
            name='boss',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
