# Generated by Django 4.2.5 on 2023-11-07 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_hui_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Инженер', max_length=16, verbose_name='Должность')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
