# Generated by Django 4.2.5 on 2023-11-08 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_role_alter_role_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='title',
            field=models.CharField(default='Инженер', max_length=64, verbose_name='Должность'),
        ),
    ]
