# Generated by Django 4.2.5 on 2023-11-08 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_role_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Номер подразделения')),
                ('title', models.CharField(default='-', max_length=250, verbose_name='Название подразделения')),
            ],
            options={
                'ordering': ('slug',),
            },
        ),
        migrations.CreateModel(
            name='DepSubLvl1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Номер')),
                ('title', models.CharField(default='-', max_length=250, verbose_name='Название подразделения')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.department', verbose_name='Подразделение')),
            ],
            options={
                'ordering': ('slug',),
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'default_related_name': 'users'},
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.role', verbose_name='Должность'),
        ),
        migrations.CreateModel(
            name='DepSubLvl2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Номер')),
                ('title', models.CharField(default='-', max_length=250, verbose_name='Название подразделения')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.depsublvl1', verbose_name='Подразделение')),
            ],
            options={
                'ordering': ('slug',),
            },
        ),
    ]
