# Generated by Django 4.2.5 on 2024-03-31 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_depsublvl1_options_alter_depsublvl2_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='users.depsublvl2', verbose_name='Подразделение'),
        ),
    ]
